config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
#     resourcesとresourceの相違点について
# 大きな違いは2つあり、それは
# ①indexアクションがあるかないか
# ②urlに:idを含むかどうか
# です。
# コメントにデストロイ機能をつけようとするとコメントにidがつく
    # コメントは特定の記事に対して何個も追加できる
    resources :comments, only: [:new, :create]
    # 自分にとって特定の記事にたいして一個しか言い値がないからresource
    resource :like, only: [:create, :destroy]
  end
  resource :profile, only: [:show, :edit, :update]
  resources :favorites, only: [:index]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  belongs_to :user
  enum gender: { male: 0, female: 1, other: 2}
  has_one_attached :avatar

  def age
    if birthday.present?
      years = Time.zone.now.year - birthday.year
      days = Time.zone.now.yday - birthday.yday
      if days < 0
        return  "#{years - 1}歳"
      else
        return  "#{years}歳"
      end
    else
      return '不明'

  
    end
  end

  end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    # if current_user.profile.present?
    #   @profile = current_user.profile
    # else
    #   @profile = current_user.build_profile
    #  end

    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新しました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :birthday,
      :subscribed,
      :avatar
    )
  end
end

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @profile, url: profile_path, method: 'put' ,local: true) do |f|
    %div 
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar
    %div
      = f.label :nickname,'ハンドルネーム'
    %div
      = f.text_field :nickname, class: 'text'
    %div
      = f.label :introduction, '自己紹介'
    %div
      = f.text_area :introduction
    %div
      = f.label :gender, '性別'
    %div
      -# f.select :gender, Profile.genders.keys, {} , {class: 'text'}
      = f.select :gender, Profile.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, { class: 'text' }
    %div
      = f.label :birthday, '生年月日'
    %div
      = f.date_field :birthday, class: 'text'
    %div
      = f.label :subscribed, '通知を受け取る'
      = f.check_box :subscribed

    = f.submit '保存', class: 'btn-primary'
    

app/views/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{current_user.display_name}（#{current_user.age}・#{I18n.t("enum.genders.#{current_user.gender}")}
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path
      .profilePage_user_introduction
        = current_user.profile&.introduction 
  - current_user.articles.each do |article|
    = render 'commons/article' , article: article
  