config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
#     resourcesとresourceの相違点について
# 大きな違いは2つあり、それは
# ①indexアクションがあるかないか
# ②urlに:idを含むかどうか
# です。
# コメントにデストロイ機能をつけようとするとコメントにidがつく
    # コメントは特定の記事に対して何個も追加できる
    resources :comments, only: [:new, :create]
    # 自分にとって特定の記事にたいして一個しか言い値がないからresource
    resource :like, only: [:create, :destroy]
  end
  resource :profile, only: [:show, :edit, :update]
  resources :favorites, only: [:index]
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  has_one_attached :eyecatch

  validates :title, presence: true
  validates :title,length: {minimum: 2 ,maximum: 100  }
  validates :title, format: { with: /\A(?!\@)/ }
  validates :content, presence: true
  validates :content, length: {minimum: 10  }
  validates :content, uniqueness: true
  validate :validate_title_content_length

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user


  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def likes_count
    likes.count
  end

  private
  def validate_title_content_length
    char_count = self.title.length + self.content.length
    unless char_count > 100
      errors.add(:content, '100文字以上で!')
    end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_articles, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article),notice:'保存できたよ'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article),notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした。'
      render :edit
    end
end

def destroy
  article = current_user.articles.find(params[:id])
  article.destroy!
  redirect_to root_path, notice: '削除に成功しました'
end

private
def article_params
  params.require(:article).permit(:title,:content,:eyecatch)
end

def set_articles
  @article = Article.find(params[:id])
  end
end

app/views/articles/_form.html.haml
.container
  %ul
    - @article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @article ,local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      =f.file_field :eyecatch
    %div
      = f.label :title,'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存',class: 'btn-primary'

app/views/articles/_tabs.html.haml
.tabs
  .tabs_item.active
    新着記事一覧
  .tabs_item
    タイムライン

app/views/articles/edit.html.haml
= render  "form" , article: @article

app/views/articles/index.html.haml
.container
  = render 'tabs'
  - @articles.each do |article|
    = render "commons/article" ,article: article
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus

app/views/articles/new.html.haml
= render  "form" , article: @article

app/views/articles/show.html.haml
.article
  - if @article.eyecatch.attached?
    .article_image 
      = image_tag @article.eyecatch
  %h1.article_title= @article.title
  .article_detail
    = image_tag @article.user.avatar_image
    %div
    
    %p= @article.author_name
    %p= @article.display_created_at
    - if user_signed_in? && current_user.has_written?(@article)
      .article_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to '編集する' ,edit_article_path(@article)
            = link_to '削除する' ,article_path(@article),data: {method: "delete" ,confirm: "本当に削除しますか？"}
    .article_content
      = @article.content
    - if user_signed_in?
      - if current_user.has_liked?(@article)
        .article_heart
          = link_to article_like_path(@article), data: {method: 'delete'} do
            = image_tag 'heart-active.svg'
      - else
        .article_heart
          = link_to article_like_path(@article), data: {method: 'post'} do
            = image_tag 'heart.svg'
.article
  %h2 コメント一覧
  -@comments.each do |comment|
    .article_comment
      %p= comment.content 

.container
  = link_to new_article_comment_path(@article) do
    .btn-secondary 
      コメントを追加